const KARAKTER = [
  {
    kunci: "kenzro",
    nama: "Kenzro",
    deskripsi: "Pemanah - jarak jauh",
    element: "Es",
    gambar: "assets/characters/kenzro.png",
    senjata: "panah",
    senjataGambar: "assets/weapons/panah.png",
    skala: 1,
    senjataSkala: 1,
    hp: 100,
    kecepatan: 360,
    attackRate: 0.25,
    damage: 25,
    reach: 0,
    halfArc: 0,
    rot: Math.PI - Math.PI / 18 - Math.PI / 12 - Math.PI / 12,
    warnaDash: "#7dd3fc",
    specialCd: 9,
    buffDurasi: 5,
    bekuDurasi: 1,
    specialRadius: 340,
    specialDmg: 100,
    tipe: "jarak"
  },
  {
    kunci: "rin",
    nama: "Vender",
    deskripsi: "Pendekar - jarak dekat",
    element: "Api",
    gambar: "assets/characters/rin.png",
    senjata: "pedang",
    senjataGambar: "assets/weapons/pedang.png",
    skala: 1,
    senjataSkala: 1,
    hp: 120,
    kecepatan: 400,
    attackRate: 0.35,
    damage: 50,
    reach: 90,
    halfArc: 1.05,
    swingDuration: 0.28,
    rot: Math.PI / 2 - Math.PI / 18,
    warnaDash: "#ff4d4d",
    specialCd: 9,
    specialRadius: 400,
    specialDmg: 60,
    tipe: "dekat"
  }
];
