param(
    [string]$PngPath = (Join-Path $PSScriptRoot "..\assets\maps\padang.png"),
    [string]$OutJs   = (Join-Path $PSScriptRoot "..\assets\maps\padang-grid.js")
)

Add-Type -AssemblyName System.Drawing

$bmp = [System.Drawing.Bitmap]::FromFile((Resolve-Path $PngPath))
$w = $bmp.Width
$h = $bmp.Height
$rect = New-Object System.Drawing.Rectangle 0, 0, $w, $h
$data = $bmp.LockBits($rect, [System.Drawing.Imaging.ImageLockMode]::ReadOnly,
    [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$scan = $data.Scan0
$numBytes = $w * $h * 4
$bytes = New-Object byte[] $numBytes
[System.Runtime.InteropServices.Marshal]::Copy($scan, $bytes, 0, $numBytes)
$bmp.UnlockBits($data)
$bmp.Dispose()

$n = $w * $h
$packed = New-Object byte[] ([math]::Ceiling($n / 8))
$countWall = 0
for ($i = 0; $i -lt $n; $i++) {
    $r = $bytes[$i * 4 + 0]
    $g = $bytes[$i * 4 + 1]
    $b = $bytes[$i * 4 + 2]
    $a = $bytes[$i * 4 + 3]
    if ($a -eq 255 -and $r -eq 0 -and $g -eq 0 -and $b -eq 0) {
        $packed[$i -shr 3] = $packed[$i -shr 3] -bor (1 -shl ($i -band 7))
        $countWall++
    }
}

$b64 = [Convert]::ToBase64String($packed)
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// GENERATED BY tools\generate-map-grid.ps1 -- JANGAN EDIT MANUAL.")
[void]$sb.AppendLine("// Grid penghalang map (1 bit/piksel, bit-set = tembok hitam murni),")
[void]$sb.AppendLine("// dikemas per-byte (LSB-first) lalu base64. Dipakai maps.js sebagai")
[void]$sb.AppendLine("// cadangan saat halaman dibuka lewat file:// dan pixel PNG tak terbaca.")
[void]$sb.AppendLine()
[void]$sb.AppendLine("const GRID_PETA_KOLOM = $w;")
[void]$sb.AppendLine("const GRID_PETA_BARIS = $h;")
[void]$sb.AppendLine("const GRID_PETA_B64 = `"$b64`";")
[void]$sb.AppendLine()

$parent = Split-Path -Parent $OutJs
if (-not (Test-Path -LiteralPath $parent)) { New-Item -ItemType Directory -Path $parent | Out-Null }
Set-Content -LiteralPath $OutJs -Value $sb.ToString() -Encoding UTF8

Write-Output ("OK: $OutJs")
Write-Output ("  Ukuran PNG : {0}x{1} px" -f $w, $h)
Write-Output ("  Piksel tembok: {0} / {1} ({2:P1})" -f $countWall, $n, ($countWall / $n))
Write-Output ("  B64        : {0} KB" -f [math]::Round($b64.Length / 1KB, 1))
